---
title: "Apply Now"
pagetitle: "Apply Now"
output:
  html_document:
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Apply Now!

Before you apply, please read the description and expectations below to ensure that this event is the right fit for you.

### What you can expect

The goal of this event is to build meaningful and sustainable connections across departments and institutions that deliver RDM in Atlantic Canada. To accomplish this, the event will:

* Feature panel discussions and topical presentations to contextualize RDM services and your role within a broader ecosystem;
* Offer breakout activities to collectively share experiences and brainstorm opportunities for collaboration;
* Create structured networking opportunities with your peers and other professionals from across the Atlantic region;
* Share co-created resources and to mobilize the ideas generated during the event;
* Aim to develop a sustainable community of practice supported by the <a href="https://www.alliancecan.ca/en" target="_blank">Digital Research Alliance of Canada (“the Alliance”)</a> and <a href="https://ace-net.ca/" target="_blank">ACENET</a>

### What we expect from you

**Successful applicants residing more than 175 km outside of the Halifax Regional Municipality will have their travel (flight or driving) and accommodation sponsored by the event organizers.** As such, participants are expected to:

* Attend and actively participate in all sessions across the two-day event;
* Engage with the event organizers in a follow-up discussion regarding your experiences;
* Share and implement co-created resources at your institution;
* Participate in the community of practice supported by the Alliance after the event’s completion.


If the event structure and expectations from you as a participant sound good, we encourage your to apply following the link below:

### <a href="https://docs.google.com/forms/d/e/1FAIpQLSeTAGJ_IE4zZtYuyEUG3z6xemKUQTMCJf0K38S_syeeLfsDSg/viewform?usp=header" target="_blank">APPLY HERE!</a>
