---
title: "Working with a Survey"
pagetitle: "Working with a Survey"
output:
  html_document:
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Working with a Survey

**Setup Pre-requisites:**

  * <a href="Block7_EXT-RRStudio.html">Download R and RStudio</a> 

**Intended audience:** Those that work with surveys in any capacity (research, registration forms, user experience testing, etc.) that have little to no experience working in R.

This workshop will focus on developing practical skills in data management that are broadly applicable to working with survey data. Using the R coding language, this day-long session is meant for those that have little to no experience with coding, with a goal to build comfort and confidence in using a coding language to make your survey workflows more efficient and reproducible.

### Section Descriptions

<br>

#### Part 1: Introduction to the R Coding Language 

This first session will provide an introduction to the R coding language, and will cover foundational literacies for those that have never used a coding language before. This is designed as a slow and encouraging session for those that might be intimidated by the idea of coding, and will give plenty of time for questions and activities. 

**Learning objectives**

By the end of this session, you'll be able to:

* Discuss pros and cons of using Excel for spreadsheet data
* Articulate the difference between Excel files (.xlsx) and plain-test .csv files, and their role in reproducibility
* Define scripting and the concept of literate programming
* Begin applying the syntax of an R script to conduct basic actions
* Create reproducible code by applying concepts of literate programming

<br>

#### Part 2: Collecting and Cleaning Survey Data 

This session will begin by introducing a mock research question, and attendees will complete a brief survey to get a sense of the data collection. We will then look at a mock dataset extracted by the survey tool, and will examine each column to see what needs to be cleaned up. Building on the skills learned in Part 1, we will explore the data in R, and go through some of the most common cleaning tasks for survey data. In addition to covering cleaning techniques, this session will also address best practices in data management, including file naming, versioning, and file management.

**Learning objectives**

By the end of this session, you'll be able to:

* Identify the types of survey questions that result in various data shapes
* Utilize RProjects as a way to promote reproducibility
* Employ the Tidyverse package as a tool to tackle data science activities
* Import a dataset into RStudio
* Explore data through a variety of functions
* Change column names in a dataset
* Add an ID column and remove columns with identifying information
* Identify concepts of wide and tidy data, and use R to make columns both wide and tidy
* Discuss considerations with data versioning, naming, and structuring

<br>

#### Part 3: Making Sense of Survey Data 

After cleaning up the data in Part 2, this session will focus on asking questions of the data and generating summaries. This will include comparing various presentations of the data that were created in Part 2, and using them to generate counts, summary tables, subsets, averages, and visualizations.

**Learning objectives**

By the end of this session, you will be able to:

* Generate counts and summary tables of data variables
* Generate basic exploratory plots 
* Filter datasets for specific criteria
* Compare averages across multiple variables and plot the results for communication

<br>


### Morning Temperature Check

Click the following link: [Morning temperature check](https://app.sli.do/event/kSUYRCDALRctX7EJoLaufE)







